### ISSUE TITLE
Should we remove "Old ALS Code" in the `ch09/1.personalization.ipynb` ?

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#119]
It doesn't work anyway...

**Comment by treygrainger** [comment]
Yep, I'll take it out. The "old" code is cleaner (python vs. SQL to map back from numbers to string ids), but doesn't currently run. Kept it there to see if I could use it to refactor later, but will just remove it and check the history if ever needed.

**Comment by treygrainger** [comment]
This was committed on Feb 12: https://github.com/treygrainger/ai-powered-search/commit/0a74eebb0c09c152fbbbbaf2492f91df0a13e131.
