### ISSUE TITLE
Improvement: refactor `docker-compose.yaml` to avoid using `container_name`

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#131]
Right now, the `container_name` is hardcoded, so when new containers are built (i.e., code has changed) they don't replace previous one, and they need to be removed explicitly. 

When doing next round of refactoring, we may need to get rid of the `container_name` and just use service names as host names

**Comment by dcrouch26** [comment]
Improvements on how the docker containers are built have been made, however needing to rebuild an image everytime docker is spun down is not desired. Images will still need to be removed to rebuild.
