### ISSUE TITLE
Some packages are installed twice, increasing the build time & image size

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#136]
Some dependencies that are specified in the `requirements.txt`, like, `transformers` are later replaced by installing `https://github.com/explosion/spacy-experimental/releases/download/v0.6.1/en_coreference_web_trf-3.4.0a2-py3-none-any.whl`:

```
en-coreference-web-trf-3.4.0a2 spacy-alignments-0.9.1 spacy-transformers-1.1.9 transformers-4.25.1
```

**Comment by dcrouch26** [comment]
`spacy-experimental` installation has been pushed to `requirements.txt` and no longer triggers redundant package installs.
