### ISSUE TITLE
Clone Command

### ISSUE THREAD

**Issue by Yosef-Ohayon** [treygrainger/ai-powered-search#150]
Hello,

Thank you for writing the book.

Please correct section A.2.  The clone command works without the .git at the end: git clone https://github.com/treygrainger/ai-powered-search

**Comment by dcrouch26** [comment]
Thanks for submitting feedback! There will be a major release in the next week. Will report back.

**Comment by alexott** [comment]
@Yosef-Ohayon This URL is what GitHub gives you when you click on the "Code" button...
