### ISSUE TITLE
Running example ch05/1.open-information-extraction.ipynb gives errors

### ISSUE THREAD

**Issue by wim-veninga** [treygrainger/ai-powered-search#195]
Steps to reproduce

1. I've cloned the git repo and ran docker compose up on the main branch.
2. I open the cha05/1.open-information-extraction.ipynb example
3. I run the first two cells, they run ok
4. The third cell (Listing 5.1) which is this code: `def generate_graph(text, lang_model, coref_model):
    parsed_text = coref_model(text)
    parsed_text = resolve_coreferences(parsed_text) # "they" => "Data Scientists"
    sentences = get_sentences(lang_model(parsed_text), lang_model) # Data Scientists also write code. => ['nsubj, 'advmod', ROOT', 'dobj', 'punct']
    
    facts = list()
    for sentence in sentences:
        facts.extend(resolve_facts(sentence, lang_model)) # subj:(Companies), rel:(employ), obj:(Data Scientists)
    return facts

text = """
Data Scientists build machine learning models. They also write code.Companies employ Data Scientists. 
Software Engineers also write code. Companies employ Software Engineers.
"""

lang_model = spacy.load("en_core_web_sm")
coref_model = spacy.load("en_coreference_web_trf")
graph = generate_graph(text, lang_model, coref_model)
for relationship in graph: print(relationship)` gives the following error: `/opt/conda/lib/python3.10/site-packages/spacy/util.py:877: UserWarning: [W095] Model 'en_core_web_sm' (3.7.1) was trained with spaCy v3.7 and may not be 100% compatible with the current version (3.4.4). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
---------------------------------------------------------------------------
RegistryError                             Traceback (most recent call last)
Cell In[3], line 16
      9     return facts
     11 text = """
     12 Data Scientists build machine learning models. They also write code.Companies employ Data Scientists. 
     13 Software Engineers also write code. Companies employ Software Engineers.
     14 """
---> 16 lang_model = spacy.load("en_core_web_sm")
     17 coref_model = spacy.load("en_coreference_web_trf")
     18 graph = generate_graph(text, lang_model, coref_model)

File /opt/conda/lib/python3.10/site-packages/spacy/__init__.py:54, in load(name, vocab, disable, enable, exclude, config)
     30 def load(
     31     name: Union[str, Path],
     32     *,
   (...)
     37     config: Union[Dict[str, Any], Config] = util.SimpleFrozenDict(),
     38 ) -> Language:
     39     """Load a spaCy model from an installed package or a local path.
     40 
     41     name (str): Package name or model path.
   (...)
     52     RETURNS (Language): The loaded nlp object.
     53     """
---> 54     return util.load_model(
     55         name,
     56         vocab=vocab,
     57         disable=disable,
     58         enable=enable,
     59         exclude=exclude,
     60         config=config,
     61     )

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:432, in load_model(name, vocab, disable, enable, exclude, config)
    430     return get_lang_class(name.replace("blank:", ""))()
    431 if is_package(name):  # installed as package
--> 432     return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
    433 if Path(name).exists():  # path to model data directory
    434     return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:468, in load_model_from_package(name, vocab, disable, enable, exclude, config)
    451 """Load a model from an installed package.
    452 
    453 name (str): The package name.
   (...)
    465 RETURNS (Language): The loaded nlp object.
    466 """
    467 cls = importlib.import_module(name)
--> 468 return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)

File /opt/conda/lib/python3.10/site-packages/en_core_web_sm/__init__.py:10, in load(**overrides)
      9 def load(**overrides):
---> 10     return load_model_from_init_py(__file__, **overrides)

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:649, in load_model_from_init_py(init_file, vocab, disable, enable, exclude, config)
    647 if not model_path.exists():
    648     raise IOError(Errors.E052.format(path=data_path))
--> 649 return load_model_from_path(
    650     data_path,
    651     vocab=vocab,
    652     meta=meta,
    653     disable=disable,
    654     enable=enable,
    655     exclude=exclude,
    656     config=config,
    657 )

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:506, in load_model_from_path(model_path, meta, vocab, disable, enable, exclude, config)
    504 overrides = dict_to_dot(config)
    505 config = load_config(config_path, overrides=overrides)
--> 506 nlp = load_model_from_config(
    507     config,
    508     vocab=vocab,
    509     disable=disable,
    510     enable=enable,
    511     exclude=exclude,
    512     meta=meta,
    513 )
    514 return nlp.from_disk(model_path, exclude=exclude, overrides=overrides)

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:554, in load_model_from_config(config, meta, vocab, disable, enable, exclude, auto_fill, validate)
    551 # This will automatically handle all codes registered via the languages
    552 # registry, including custom subclasses provided via entry points
    553 lang_cls = get_lang_class(nlp_config["lang"])
--> 554 nlp = lang_cls.from_config(
    555     config,
    556     vocab=vocab,
    557     disable=disable,
    558     enable=enable,
    559     exclude=exclude,
    560     auto_fill=auto_fill,
    561     validate=validate,
    562     meta=meta,
    563 )
    564 return nlp

File /opt/conda/lib/python3.10/site-packages/spacy/language.py:1764, in Language.from_config(cls, config, vocab, disable, enable, exclude, meta, auto_fill, validate)
   1762     filled["pretraining"] = orig_pretraining
   1763     config["pretraining"] = orig_pretraining
-> 1764 resolved_nlp = registry.resolve(
   1765     filled["nlp"], validate=validate, schema=ConfigSchemaNlp
   1766 )
   1767 create_tokenizer = resolved_nlp["tokenizer"]
   1768 before_creation = resolved_nlp["before_creation"]

File /opt/conda/lib/python3.10/site-packages/confection/__init__.py:760, in registry.resolve(cls, config, schema, overrides, validate)
    751 @classmethod
    752 def resolve(
    753     cls,
   (...)
    758     validate: bool = True,
    759 ) -> Dict[str, Any]:
--> 760     resolved, _ = cls._make(
    761         config, schema=schema, overrides=overrides, validate=validate, resolve=True
    762     )
    763     return resolved

File /opt/conda/lib/python3.10/site-packages/confection/__init__.py:809, in registry._make(cls, config, schema, overrides, resolve, validate)
    807 if not is_interpolated:
    808     config = Config(orig_config).interpolate()
--> 809 filled, _, resolved = cls._fill(
    810     config, schema, validate=validate, overrides=overrides, resolve=resolve
    811 )
    812 filled = Config(filled, section_order=section_order)
    813 # Check that overrides didn't include invalid properties not in config

File /opt/conda/lib/python3.10/site-packages/confection/__init__.py:863, in registry._fill(cls, config, schema, validate, resolve, parent, overrides)
    861     field = schema.__fields__[key]
    862     schema.__fields__[key] = copy_model_field(field, Any)
--> 863 promise_schema = cls.make_promise_schema(value, resolve=resolve)
    864 filled[key], validation[v_key], final[key] = cls._fill(
    865     value,
    866     promise_schema,
   (...)
    870     overrides=overrides,
    871 )
    872 reg_name, func_name = cls.get_constructor(final[key])

File /opt/conda/lib/python3.10/site-packages/confection/__init__.py:1069, in registry.make_promise_schema(cls, obj, resolve)
   1067 if not resolve and not cls.has(reg_name, func_name):
   1068     return EmptySchema
-> 1069 func = cls.get(reg_name, func_name)
   1070 # Read the argument annotations and defaults from the function signature
   1071 id_keys = [k for k in obj.keys() if k.startswith("@")]

File /opt/conda/lib/python3.10/site-packages/spacy/util.py:127, in registry.get(cls, registry_name, func_name)
    125 if not hasattr(cls, registry_name):
    126     names = ", ".join(cls.get_registry_names()) or "none"
--> 127     raise RegistryError(Errors.E892.format(name=registry_name, available=names))
    128 reg = getattr(cls, registry_name)
    129 try:

RegistryError: [E892] Unknown function registry: 'vectors'.

Available names: architectures, augmenters, batchers, callbacks, cli, datasets, displacy_colors, factories, initializers, languages, layers, lemmatizers, loggers, lookups, losses, misc, models, ops, optimizers, readers, schedules, scorers, tokenizers`

There seems to be a version conflict (as least according to chatgpt), I've followed all of the steps in this chat, but I haven't been able to resolve this issue. I'm running mac os sonoma 14.1. https://chatgpt.com/share/56e560a9-87ba-4f44-8b1c-d8d9af3cc304

**Comment by dcrouch26** [comment]
Hey thanks for reporting this issue, I've stubbed this listing out for some consideration on it's effects on the environment because this isn't the only issue it's having. This fix is currently in `main`
