### ISSUE TITLE
solr container not responding

### ISSUE THREAD

**Issue by biwa7636** [treygrainger/ai-powered-search#25]
I was able to run `docker-compose up` and access the notebook but the solr container failed to start. 

1. It first failed the health check in the `welcome.ipynb` with the error message 
```
Error! One or more containers are not responding.
Please follow the instructions in Appendix A.
```

2. looking inside the docker-compose up log, the aips-solr failed to start 
```
$ docker-compose down && docker-compose up
Removing aips-data-science ...
Removing aips-solr         ...
...
Creating aips-data-science ...
Creating aips-data-science ... done
Attaching to aips-zk, aips-solr, aips-data-science

aips-solr    | /bin/sh: 0: Can't open                         <--------------  cannot open 
aips-zk      | ZooKeeper JMX enabled by default
...
ps-zk      | 2021-05-09 18:08:19,839 [myid:1] - WARN  [main:QuorumPeerMain@125] - Either no config or no quorum defined in config, running  in standalone mode
aips-solr exited with code 127                               <-------------- failed with code error 127
...
```

I am using Windows10 Docker Desktop v20.10.5 and integration with WSL 2 distro Ubuntu-18.04. 
I tried to ran the docker-compose up inside both the WSL, Powershell and Git Bash, all failed to start Solr.

Anyone else with this error message?

**Comment by tanjie123** [comment]
I have the same problem.

**Comment by tanjie123** [comment]
docker build -f Dockerfile -t apis-solr .

**Comment by treygrainger** [comment]
I'll check this out over the next two weeks and see what's needed to get it working in that environment. I'm going through and doing some dependency and container updates to better support arm64 environments (like the new Mac M1 systems). That's not your issue here, but hopefully in the process of those updates whatever this is can be fixed as well.

**Comment by streuselcake** [comment]
I had to change the line endings of the two shell scripts docker/solr/launch_solr.sh and docker/solr/run_solr_w_ltr.sh from <cr>+<lf> to <lf> for the scripts to work. This is a common, but painful problem windows users run into as it can be hard to figure out what is going on. @treygrainger it may be useful to perhaps add a line ending configuration to a .gitattributes and/or add a hint in the readme or welcome notebook?

Happy searching!

**Comment by treygrainger** [comment]
@streuselcake - was the line endings the specific fix for the issue that biwa7636 reported?

Are you running those scripts outside of Docker (directly in windows)?

Also @biwa7636 - is this still a problem. Have made multiple changes since this was originally reported, so wondering if this has been fixed? If not, I can try to replicate your system specs and reproduce on my end.

**Comment by streuselcake** [comment]
@treygrainger using correct line endings fixes the problem for shellscripts running in docker containers (and in general, I think) but there is nothing to fix in the repo I think. 

The lineendings are wrong in all .sh-scripts when checked out via git when configured to use cr+lf line endings (windows default) locally. The solr start script fails with cr+lf line endings. However, the run_solr_w_ltr.sh and launch_solr.sh look fine, when checked out as is  (lf only as lineendings). 

Cheers!

**Comment by treygrainger** [comment]
Sorry for the delay in solving this. Seems to have been an issue with the mixed environment (WSL) context. I got WSL2 setup on a Windows system to reproduce and the gitattributes fix unfortunately didn't work (but I put it in anyway to keep things clean in the future). Ultimately needed to modify the Dockerfile to explicitly replace line endings in the shell script to get this to work.

At any rate, should be resolved now in the master branch. Thanks for reporting and for the insight re: the line endings on WSL.
