### ISSUE TITLE
Chapter 13 Download Data set fails

### ISSUE THREAD

**Issue by joshsgoldstein** [treygrainger/ai-powered-search#34]
when running this part of the code

```
def download_outdoors_dataset():
    from ltr.download import download, extract_tgz
    import tarfile

    dataset = ['https://github.com/ai-powered-search/outdoors/raw/master/outdoors.tgz']
    download(dataset, dest='data/')
    extract_tgz('data/outdoors.tgz') # -> Holds 'outdoors.csv', a big CSV file of the stackexchange outdoors dataset
    
```

Receiving this error:

`ReadError: not a gzip file`

Inside the gz file is a bunch of html I do not see any csv files

**Comment by raphael10-collab** [comment]
@joshsgoldstein Have you managed to use Chapt 13's code?

![image](https://user-images.githubusercontent.com/70313067/143446655-5f33cb52-0512-4c4d-8e22-e71f7366f7a5.png)

**Comment by streuselcake** [comment]
I'm getting a 404 for https://github.com/ai-powered-search/outdoors/raw/master/outdoors.tgz and there are multiple parts for the dataset here https://github.com/ai-powered-search/outdoors/

**Comment by alexott** [comment]
check the `spark3-support` branch

**Comment by treygrainger** [comment]
This was fixed a while back, so I'm marking the issue as closed. If anyone else has any dataset issues, please let me know (re-open or file a new issue). Thanks!
