### ISSUE TITLE
Make Retrotech Search Dataset Available

### ISSUE THREAD

**Issue by jrjames83** [treygrainger/ai-powered-search#47]
![image](https://user-images.githubusercontent.com/11641974/147953485-e3ebaf2c-c5b6-44ef-a806-3c5ab8701f6c.png)

Howdy, enjoying the book! Can you add the Retrotech search sessions dataset? This would be to play around with the data referenced in chapter 11 regarding SDBM's. 

https://github.com/treygrainger/ai-powered-search/tree/master/docker/data-science/notebooks/data/retrotech

or perhaps to the spark-3-support branch (to support the working pip installable branch, per https://github.com/treygrainger/ai-powered-search/issues/46)

Thank you!

**Comment by alexott** [comment]
many datasets in their own repositories. Retrotech is here: https://github.com/ai-powered-search/retrotech

**Comment by jrjames83** [comment]
Thank you @alexott !
