### ISSUE TITLE
docker-compose up load error:   solr.jvm:memory.heap.used

### ISSUE THREAD

**Issue by robhedg** [treygrainger/ai-powered-search#50]
Has anyone seen this error / warning message before?  Any ideas on how to fix it? 

aips-solr    | 2022-01-16 15:44:19.671 INFO  (qtp1962329560-20) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/metrics params={wt=javabin&version=2&key=solr.jvm:os.processCpuLoad&key=solr.node:CONTAINER.fs.coreRoot.usableSpace&key=solr.jvm:os.systemLoadAverage&key=solr.jvm:memory.heap.used} status=0 QTime=26

Full docker-compose up logs attached.
[docker jvm memory prob.txt](https://github.com/treygrainger/ai-powered-search/files/7877327/docker.jvm.memory.prob.txt)

**Comment by ballabusta** [comment]
I believe that's not a problem, solr heap is used during the collection indexing. Also status=0 tells you the request is successful.

**Comment by treygrainger** [comment]
Just looks like a Solr metric being collected to keep track of JVM heap usage. Doesn't seem like there's any problem here. If you run into any issues, feel free to re-open the issue, though.
