### ISSUE TITLE
outdoors dataset in notebook ch5/2.index-datasets

### ISSUE THREAD

**Issue by streuselcake** [treygrainger/ai-powered-search#53]
Because https://github.com/ai-powered-search/outdoors.git doesn't contain a single tar file, I changed the following line in notebook ch5/2.index-datasets

```
! cd outdoors && mkdir -p '../../data/outdoors/' && tar -xvf outdoors.tgz -C '../../data/outdoors/'
```
to
``` 
! cd outdoors && mkdir -p '../../data/outdoors/' && cat outdoors.tgz* | tar -xz && cp posts.csv ../../data/outdoors
```

The download and notebook seem to work now but I am not sure if my solution is appropriate?

**Comment by alexott** [comment]
check the `spark3-support` branch...

**Comment by treygrainger** [comment]
Thanks for reporting! This was fixed a while back, so I'm closing out the issue.
