### ISSUE TITLE
Appendix A: error running healthcheck

### ISSUE THREAD

**Issue by kchang808** [treygrainger/ai-powered-search#54]
I get the following error when running healthcheck.  I tried doing this as a reply on Manning but ran into a 5K char limit as well as posting consecutive comments so I put my issue here.

Error! One or more containers are not responding.
Please follow the instructions in Appendix A.

I am running this on Windows 10 using Windows Terminal/Powershell

From the command line I ran this to check the docker-compose version

PS C:\kendevelopment\ai-powered-search\docker> docker-compose --version
docker-compose version 1.29.2, build 5becea4c

Then I run docker-compose up and here's the output.

PS C:\kendevelopment\ai-powered-search\docker> docker-compose up
Creating network "docker_zk-solr" with the default driver
Creating network "docker_solr-data-science" with the default driver
Creating aips-zk ... done
Creating aips-solr ... done
Creating aips-data-science ... done
Attaching to aips-zk, aips-solr, aips-data-science
: No such file /bin/sh: 0: cannot open
aips-zk      | ZooKeeper JMX enabled by default
aips-zk      | Using config: /conf/zoo.cfg
aips-zk      | 2022-04-01 14:00:43,938 [myid:] - INFO  [main:QuorumPeerConfig@133] - Reading configuration from: /conf/zoo.cfg
aips-zk      | 2022-04-01 14:00:43,945 [myid:] - INFO  [main:QuorumPeerConfig@375] - clientPort is not set
aips-zk      | 2022-04-01 14:00:43,945 [myid:] - INFO  [main:QuorumPeerConfig@389] - secureClientPort is not set
aips-zk      | 2022-04-01 14:00:43,954 [myid:] - ERROR [main:QuorumPeerConfig@645] - Invalid configuration, only one server specified (ignoring)
aips-zk      | 2022-04-01 14:00:43,960 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
aips-zk      | 2022-04-01 14:00:43,961 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
aips-zk      | 2022-04-01 14:00:43,961 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
aips-zk      | 2022-04-01 14:00:43,961 [myid:1] - WARN  [main:QuorumPeerMain@125] - Either no config or no quorum defined in config, running  in standalone mode
aips-zk      | 2022-04-01 14:00:43,964 [myid:1] - INFO  [main:ManagedUtil@46] - Log4j found with jmx enabled.
aips-zk      | 2022-04-01 14:00:43,976 [myid:1] - INFO  [main:QuorumPeerConfig@133] - Reading configuration from: /conf/zoo.cfg
aips-zk      | 2022-04-01 14:00:43,976 [myid:1] - INFO  [main:QuorumPeerConfig@375] - clientPort is not set
aips-zk      | 2022-04-01 14:00:43,977 [myid:1] - INFO  [main:QuorumPeerConfig@389] - secureClientPort is not set
aips-zk      | 2022-04-01 14:00:43,977 [myid:1] - ERROR [main:QuorumPeerConfig@645] - Invalid configuration, only one server specified (ignoring)
aips-zk      | 2022-04-01 14:00:43,977 [myid:1] - INFO  [main:ZooKeeperServerMain@117] - Starting server
aips-zk      | 2022-04-01 14:00:44,040 [myid:1] - INFO  [main:Environment@109] - Server environment:zookeeper.version=3.5.5-390fe37ea45dee01bf87dc1c042b5e3dcce88653, built on 05/03/2019 12:07 GMT
aips-zk      | 2022-04-01 14:00:44,040 [myid:1] - INFO  [main:Environment@109] - Server environment:host.name=aips-zk
aips-zk      | 2022-04-01 14:00:44,042 [myid:1] - INFO  [main:Environment@109] - Server environment:java.version=1.8.0_232
aips-zk      | 2022-04-01 14:00:44,042 [myid:1] - INFO  [main:Environment@109] - Server environment:java.vendor=Oracle Corporation
aips-zk      | 2022-04-01 14:00:44,042 [myid:1] - INFO  [main:Environment@109] - Server environment:java.home=/usr/local/openjdk-8
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:java.class.path=/apache-zookeeper-3.5.5-bin/bin/../zookeeper-server/target/classes:/apache-zookeeper-3.5.5-bin/bin/../build/classes:/apache-zookeeper-3.5.5-bin/bin/../zookeeper-server/target/lib/*.jar:/apache-zookeeper-3.5.5-bin/bin/../build/lib/*.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/zookeeper-jute-3.5.5.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/zookeeper-3.5.5.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/slf4j-log4j12-1.7.25.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/slf4j-api-1.7.25.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/netty-all-4.1.29.Final.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/log4j-1.2.17.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/json-simple-1.1.1.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jline-2.11.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-util-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-servlet-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-server-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-security-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-io-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jetty-http-9.4.17.v20190418.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/javax.servlet-api-3.1.0.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jackson-databind-2.9.8.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jackson-core-2.9.8.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/jackson-annotations-2.9.0.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/commons-cli-1.2.jar:/apache-zookeeper-3.5.5-bin/bin/../lib/audience-annotations-0.5.0.jar:/apache-zookeeper-3.5.5-bin/bin/../zookeeper-*.jar:/apache-zookeeper-3.5.5-bin/bin/../zookeeper-server/src/main/resources/lib/*.jar:/conf:
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:java.io.tmpdir=/tmp
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:java.compiler=<NA>
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:os.name=Linux
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:os.arch=amd64
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:os.version=5.10.102.1-microsoft-standard-WSL2
aips-zk      | 2022-04-01 14:00:44,043 [myid:1] - INFO  [main:Environment@109] - Server environment:user.name=zookeeper
aips-zk      | 2022-04-01 14:00:44,044 [myid:1] - INFO  [main:Environment@109] - Server environment:user.home=/home/zookeeper
aips-zk      | 2022-04-01 14:00:44,044 [myid:1] - INFO  [main:Environment@109] - Server environment:user.dir=/apache-zookeeper-3.5.5-bin
aips-zk      | 2022-04-01 14:00:44,044 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.free=367MB
aips-zk      | 2022-04-01 14:00:44,044 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.max=889MB
aips-zk      | 2022-04-01 14:00:44,044 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.total=379MB
aips-zk      | 2022-04-01 14:00:44,048 [myid:1] - INFO  [main:ZooKeeperServer@938] - minSessionTimeout set to 4000
aips-zk      | 2022-04-01 14:00:44,048 [myid:1] - INFO  [main:ZooKeeperServer@947] - maxSessionTimeout set to 40000
aips-zk      | 2022-04-01 14:00:44,049 [myid:1] - INFO  [main:ZooKeeperServer@166] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /datalog/version-2 snapdir /data/version-2
aips-zk      | 2022-04-01 14:00:44,084 [myid:1] - INFO  [main:Log@193] - Logging initialized @772ms to org.eclipse.jetty.util.log.Slf4jLog
aips-zk      | 2022-04-01 14:00:44,184 [myid:1] - WARN  [main:ContextHandler@1588] - o.e.j.s.ServletContextHandler@cb644e{/,null,UNAVAILABLE} contextPath ends with /*
aips-zk      | 2022-04-01 14:00:44,184 [myid:1] - WARN  [main:ContextHandler@1599] - Empty contextPath
aips-zk      | 2022-04-01 14:00:44,198 [myid:1] - INFO  [main:Server@370] - jetty-9.4.17.v20190418; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67; jvm 1.8.0_232-b09
aips-zk      | 2022-04-01 14:00:44,259 [myid:1] - INFO  [main:DefaultSessionIdManager@365] - DefaultSessionIdManager workerName=node0
aips-zk      | 2022-04-01 14:00:44,259 [myid:1] - INFO  [main:DefaultSessionIdManager@370] - No SessionScavenger set, using defaults
aips-zk      | 2022-04-01 14:00:44,262 [myid:1] - INFO  [main:HouseKeeper@149] - node0 Scavenging every 600000ms
aips-zk      | 2022-04-01 14:00:44,297 [myid:1] - INFO  [main:ContextHandler@855] - Started o.e.j.s.ServletContextHandler@cb644e{/,null,AVAILABLE}
aips-zk      | 2022-04-01 14:00:44,327 [myid:1] - INFO  [main:AbstractConnector@292] - Started ServerConnector@100fc185{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
aips-zk      | 2022-04-01 14:00:44,327 [myid:1] - INFO  [main:Server@410] - Started @1031ms
aips-zk      | 2022-04-01 14:00:44,328 [myid:1] - INFO  [main:JettyAdminServer@112] - Started AdminServer on address 0.0.0.0, port 8080 and command URL /commands
aips-zk      | 2022-04-01 14:00:44,333 [myid:1] - INFO  [main:ServerCnxnFactory@135] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
aips-zk      | 2022-04-01 14:00:44,338 [myid:1] - INFO  [main:NIOServerCnxnFactory@673] - Configuring NIO connection handler with 10s sessionless connection timeout, 2 selector thread(s), 16 worker threads, and 64 kB direct buffers.
aips-zk      | 2022-04-01 14:00:44,339 [myid:1] - INFO  [main:NIOServerCnxnFactory@686] - binding to port /0.0.0.0:2181
aips-zk      | 2022-04-01 14:00:44,356 [myid:1] - INFO  [main:ZKDatabase@117] - zookeeper.snapshotSizeFactor = 0.33
aips-zk      | 2022-04-01 14:00:44,359 [myid:1] - INFO  [main:FileTxnSnapLog@372] - Snapshotting: 0x0 to /data/version-2/snapshot.0
aips-zk      | 2022-04-01 14:00:44,362 [myid:1] - INFO  [main:FileTxnSnapLog@372] - Snapshotting: 0x0 to /data/version-2/snapshot.0
aips-zk      | 2022-04-01 14:00:44,376 [myid:1] - INFO  [main:ContainerManager@64] - Using checkIntervalMs=60000 maxPerMinute=10000
aips-solr exited with code 2
aips-data-science | [I 14:00:46.559 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
aips-data-science | [W 14:00:47.634 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
aips-data-science | [W 14:00:47.659 NotebookApp] Error loading server extension jupyterlab
aips-data-science |     Traceback (most recent call last):
aips-data-science |       File "/home/jovyan/.local/lib/python3.7/site-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
aips-data-science |         mod = importlib.import_module(modulename)
aips-data-science |       File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
aips-data-science |         return _bootstrap._gcd_import(name[level:], package, level)
aips-data-science |       File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
aips-data-science |       File "<frozen importlib._bootstrap>", line 983, in _find_and_load
aips-data-science |       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
aips-data-science |       File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
aips-data-science |       File "<frozen importlib._bootstrap_external>", line 728, in exec_module
aips-data-science |       File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
aips-data-science |       File "/opt/conda/lib/python3.7/site-packages/jupyterlab/__init__.py", line 7, in <module>
aips-data-science |         from .labapp import LabApp
aips-data-science |       File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 15, in <module>
aips-data-science |         from jupyter_server.serverapp import flags
aips-data-science |       File "/opt/conda/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 40, in <module>
aips-data-science |         from jupyter_core.paths import secure_write
aips-data-science |     ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (/home/jovyan/.local/lib/python3.7/site-packages/jupyter_core/paths.py)
aips-data-science | [I 14:00:47.664 NotebookApp] Serving notebooks from local directory: /home/jovyan/notebooks
aips-data-science | [I 14:00:47.664 NotebookApp] The Jupyter Notebook is running at:
aips-data-science | [I 14:00:47.664 NotebookApp] http://(4214d2bd0462 or 127.0.0.1):8888/
aips-data-science | [I 14:00:47.664 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Everything looks OK except for an "aips-solr exited with code 2" message.  I would think solr should be running.

In a separate Windows Terminal windows I run docker-compose ps

PS C:\kendevelopment\ai-powered-search\docker> docker-compose ps
      Name                     Command               State                                                            Ports
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
aips-data-science   tini -g -- /bin/bash -o pi ...   Up       0.0.0.0:2345->2345/tcp, 0.0.0.0:7077->7077/tcp, 0.0.0.0:8082->8080/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8888->8888/tcp
aips-solr           /bin/sh -c "./run_solr_w_l ...   Exit 2
aips-zk             /docker-entrypoint.sh zkSe ...   Up       0.0.0.0:2181->2128/tcp, 2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp
PS C:\kendevelopment\ai-powered-search\docker>

aips-solr with a state of Exit 2 is probably not good. Then went to http://localhost:8888/notebooks/welcome.ipynb

And ran the Healthcheck

Error! One or more containers are not responding.
Please follow the instructions in Appendix A.

Thanks for your help.  Thanks for writing this as I'm really motivated to learn this.

**Comment by streuselcake** [comment]
": No such file /bin/sh: 0: cannot open" 
might be the line endings problem with shell scripts I mentioned here: https://github.com/treygrainger/ai-powered-search/issues/25#issuecomment-1074940872

Perhaps check and change line endings in docker/solr/launch_solr.sh and docker/solr/run_solr_w_ltr.sh from cr+lf to lf.

**Comment by nishit-rapidops** [comment]
Can you please share the changed files? I am also facing the same issue.

**Comment by streuselcake** [comment]
The files are in the repository, but lineendings in your local filesystem after checkout will change depending on your git config.

**Comment by crowmedia** [comment]
I changed the lineendings as @streuselcake  said. But this was not the solution for me. So I run launch_solr.sh but like that #!/bin/sh

docker build . -t docker_solr 

without docker-compose up. After that I went to the docker folder and run the docker-compose up

**Comment by ThierryGirod** [comment]
Can confirm the workaround of @crowmedia. I had also to change first the lineendings and then the manual building helped me to start the container.

**Comment by terencenwk** [comment]
This can be fixed by setting:
git config --global core.autocrlf false

then checkout again the repository.

**Comment by treygrainger** [comment]
Hi everyone, I just pushed a fix to the repository that should permanently fix this regardless of OS. Ultimately ended up explicitly correcting the line ending in the affected file instead of trying to do it with .gitattributes along because there were various edge cases that that didn't always cover.

If you were having this issue before, can you please try pulling again and let me know if all is good or if you still have any problems? Thanks!

**Comment by treygrainger** [comment]
Going to mark this as closed, as all should be resolved. If anyone continues to have issues, please reopen or submit a new issue to let me know. Thanks!
