### ISSUE TITLE
ch5 - Notebook 2.index-datasets.ipynb not able to open

### ISSUE THREAD

**Issue by MarkusOdenthal** [treygrainger/ai-powered-search#68]
Hello,

First of all, this is an awesome book. Currently, I'm working with it day and night. :D 

right now I'm in Chapter 5, but since the last commit 2.index-datasets.ipynb is broken. In commit `7cbf560aa9b4fb12a6b453b819e716774984e397` it works but after this not anymore. 

I get the following error if I try to open it:
`NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html la...")`

**Comment by My3VM** [comment]
yes, same issue troubling me too!

**Comment by alexott** [comment]
@treygrainger can you please resubmit 2nd notebook in chapter 5? Right now it's HTML of the github page instead of `.ipynb`

**Comment by treygrainger** [comment]
Sorry everyone, I've been heads-down focused on getting chapter 7 finished (should be released in the next MEAP very soon). Now that I'm done with that, I'm back to cleaning up other outstanding issues.

I'll take a look at this one and get it fixed by tomorrow. Thanks!

**Comment by treygrainger** [comment]
This has been fixed in master. Sorry for the inconvenience!
