### ISSUE TITLE
Rename code for chapters from `ch3`, `ch4`, ... to `ch03`, `ch04`, ... so they will be in the right order

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#84]
This is how it looks like right now:

![This is how it looks like right now](https://github.com/treygrainger/ai-powered-search/assets/30342/0ee52acb-a579-4aa7-bbd0-74b2e101d544)

Chapter 10, 11, ... are shown before Chapter 3, 4, 5, ...

**Comment by treygrainger** [comment]
Addressed in https://github.com/treygrainger/ai-powered-search/pull/113
