### ISSUE TITLE
Should we commit results in the notebooks?

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#85]
If we're expecting that people will run the code in the notebooks, should we strip results from them, or leave committed?

With results in, it's a bit harder to do code reviews, etc.

**Comment by treygrainger** [comment]
I prefer to commit the results. This accomplishes two things:
1. Someone can easily load the notebook in github or elsewhere and walk through the code without actually having to run it. They see the code AND the output, so there's not actual need to run the code unless they want to tinker with it or the running systems.

2. It makes it easier when running the examples to verify all is working as expected. If the results generated aren't deterministic and they change on a future run, this indicates a problem somewhere.

**Comment by alexott** [comment]
Thank you for clarification Trey!
