### ISSUE TITLE
"Up next" link in `ch5/3.semantic-knowledge-graph.ipynb` points to Chapter 10, not Chapter 6

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#88]
https://github.com/treygrainger/ai-powered-search/blob/main/docker/data-science/notebooks/ch5/3.semantic-knowledge-graph.ipynb?short_path=b296569#L867

**Comment by alexott** [comment]
Same in:

- `ch6/1.skg-classification-disambiguation.ipynb`

**Comment by treygrainger** [comment]
Fixed
