### ISSUE TITLE
`ch7/2.semantic-search.ipynb` - no example of use for defined functions

### ISSUE THREAD

**Issue by alexott** [treygrainger/ai-powered-search#96]
The notebook defines a bunch of different functions but doesn't show how to use them

**Comment by treygrainger** [comment]
I'll be working on ch7 thoroughly next week and will review this then.

**Comment by treygrainger** [comment]
Fixed with https://github.com/treygrainger/ai-powered-search/commit/879b729b02443ad24a6969b13fd5b4ab22290006
